SOLR_TGZ_URL ?= http://apache.mirrors.tds.net/lucene/solr/4.2.1/solr-4.2.1.tgz
PORT         ?= 8983
IP           ?= 0.0.0.0

CORENAME     ?= maincore

export

schema-xml:
	python manage.py build_solr_schema > solr/solr/${CORENAME}/conf/schema.xml 2> /dev/null

solr-instance:
	make -C solr/ $@

clean:
	make -C solr/ $@

mrproper:
	make -C solr/ $@

.PHONY: schema-xml solr-instance clean mrproper
