try:
    import shortuuid
except ImportError:
    shortuuid = None

from django.conf.urls.defaults import *
from storybase_user.views import (OrganizationDetailView, OrganizationListView,
    OrganizationShareView, OrganizationSharePopupView,
    OrganizationEmbedView, OrganizationEmbedPopupView, 
    OrganizationWidgetView, ProjectDetailView,
    ProjectListView, ProjectShareView, ProjectSharePopupView,
    ProjectEmbedView, ProjectEmbedPopupView, 
    ProjectWidgetView, UserProfileDetailView,
    UserProfileShareView, UserProfileSharePopupView,
    CreateOrganizationView, CreateProjectView)
   
urlpatterns = patterns('',
    url(r'organizations/$', OrganizationListView.as_view(),
        name='organization_list'),
    url(r'organizations/(?P<organization_id>[0-9a-f]{32,32})/$',
        OrganizationDetailView.as_view(), name='organization_detail_by_id'),
    url(r'organizations/(?P<slug>[0-9a-z-]+)/$',
        OrganizationDetailView.as_view(), name='organization_detail'),
    url(r'organizations/(?P<organization_id>[0-9a-f]{32,32})/widget/$',
        OrganizationWidgetView.as_view(),
        name='organization_widget'),
    url(r'organizations/(?P<slug>[0-9a-z-]+)/widget/$',
        OrganizationWidgetView.as_view(),
        name='organization_widget'),
    url(r'organizations/(?P<organization_id>[0-9a-f]{32,32})/share/$',
        OrganizationShareView.as_view(),
        name='organization_share'),
    url(r'organizations/(?P<slug>[0-9a-z-]+)/share/$',
        OrganizationShareView.as_view(),
        name='organization_share'),
    url(r'organizations/(?P<organization_id>[0-9a-f]{32,32})/share/popup/$',
        OrganizationSharePopupView.as_view(),
        name='organization_share_popup'),
    url(r'organizations/(?P<slug>[0-9a-z-]+)/share/popup/$',
        OrganizationSharePopupView.as_view(),
        name='organization_share_popup'),
    url(r'organizations/(?P<organization_id>[0-9a-f]{32,32})/embed/$',
        OrganizationEmbedView.as_view(),
        name='organization_embed'),
    url(r'organizations/(?P<slug>[0-9a-z-]+)/embed/$',
        OrganizationEmbedView.as_view(),
        name='organization_embed'),
    url(r'organizations/(?P<organization_id>[0-9a-f]{32,32})/embed/popup/$',
        OrganizationEmbedPopupView.as_view(),
        name='organization_embed_popup'),
    url(r'organizations/(?P<slug>[0-9a-z-]+)/embed/popup/$',
        OrganizationEmbedPopupView.as_view(),
        name='organization_embed_popup'),
    url(r'create-organization/$', CreateOrganizationView.as_view(),
        name='create_organization'),
    url(r'projects/$', ProjectListView.as_view(), name='project_list'),
    url(r'projects/(?P<project_id>[0-9a-f]{32,32})/$',
        ProjectDetailView.as_view(), name='project_detail_by_id'), 
    url(r'projects/(?P<slug>[0-9a-z-]+)/$',
        ProjectDetailView.as_view(), name='project_detail'), 
    url(r'projects/(?P<project_id>[0-9a-f]{32,32})/widget/$',
        ProjectWidgetView.as_view(), name='project_widget'), 
    url(r'projects/(?P<slug>[0-9a-z-]+)/widget/$',
        ProjectWidgetView.as_view(), name='project_widget'), 
    url(r'projects/(?P<project_id>[0-9a-f]{32,32})/share/$',
        ProjectShareView.as_view(), name='project_share'), 
    url(r'projects/(?P<slug>[0-9a-z-]+)/share/$',
        ProjectShareView.as_view(), name='project_share'),
    url(r'projects/(?P<project_id>[0-9a-f]{32,32})/share/popup/$',
        ProjectSharePopupView.as_view(), name='project_share_popup'), 
    url(r'projects/(?P<slug>[0-9a-z-]+)/share/popup/$',
        ProjectSharePopupView.as_view(), name='project_share_popup'),
    url(r'projects/(?P<project_id>[0-9a-f]{32,32})/embed/$',
        ProjectEmbedView.as_view(),
        name='project_embed'),
    url(r'projects/(?P<slug>[0-9a-z-]+)/embed/$',
        ProjectEmbedView.as_view(),
        name='project_embed'),
    url(r'projects/(?P<project_id>[0-9a-f]{32,32})/embed/popup/$',
        ProjectEmbedPopupView.as_view(),
        name='project_embed_popup'),
    url(r'projects/(?P<slug>[0-9a-z-]+)/embed/popup/$',
        ProjectEmbedPopupView.as_view(),
        name='project_embed_popup'),
    url(r'create-project/$', CreateProjectView.as_view(),
        name='create_project'),
    url(r'users/(?P<profile_id>[0-9a-f]{32,32})/$', 
        UserProfileDetailView.as_view(), name='userprofile_detail'),
    url(r'users/(?P<profile_id>[0-9a-f]{32,32})/share/$', 
        UserProfileShareView.as_view(),
        name='userprofile_share'),
    url(r'users/(?P<profile_id>[0-9a-f]{32,32})/share/popup/$', 
        UserProfileSharePopupView.as_view(),
        name='userprofile_share_popup'),
)

if shortuuid:
    alphabet = shortuuid.get_alphabet()
    urlpatterns = urlpatterns + patterns('',
        url(r"users/(?P<short_profile_id>[%s]+)/$" % (alphabet), 
            UserProfileDetailView.as_view(), name='userprofile_detail'),
        url(r"users/(?P<short_profile_id>[%s]+)/share/$" % (alphabet), 
            UserProfileShareView.as_view(),
            name='userprofile_share'),
        url(r"users/(?P<short_profile_id>[%s]+)/share/popup/$" % (alphabet), 
            UserProfileSharePopupView.as_view(),
            name='userprofile_share_popup'),
    )
