SETTING_ATTRS = ('ADDTHIS_PUBID', 'GA_PROPERTY_ID', 'GA_DOMAIN_NAME',
                'STORYBASE_SITE_NAME', 'STORYBASE_SITE_TAGLINE',
                'STORYBASE_EXPLORE_TITLE', 
                'STORYBASE_ORGANIZATION_LIST_TITLE',
                'STORYBASE_PROJECT_LIST_TITLE', 'STORYBASE_MAP_CENTER',
                'STORYBASE_MAP_ZOOM_LEVEL',
                'STORYBASE_MAP_POINT_ZOOM_LEVEL',
                'STORYBASE_SEARCH_DISTANCE',
                'STORYBASE_CONTACT_EMAIL', 
                'STORYBASE_CONNECTED_STORY_TEMPLATE')
JSON_SETTINGS = ('STORYBASE_MAP_CENTER',)
