"""URL routing for storybase_story app"""
from django.conf import settings
from django.conf.urls import patterns, url

from storybase_story.feeds import StoriesFeed, TopicStoriesFeed
from storybase_story.views import (ExploreStoriesView, 
    StoryBuilderView, StoryDetailView, StoryViewerView,
    StoryUpdateView, StoryShareView, StorySharePopupView,
    StoryEmbedView, StoryEmbedPopupView, HomeView)


uuid_pattern = settings.UUID_PATTERN

urlpatterns = patterns('',
    url(r'^home/$', HomeView.as_view(), name='home'),
    url(r'^build/$', StoryBuilderView.as_view(), name='story_builder'),
    url(r'^build/(?P<story_id>{})/$'.format(uuid_pattern),
        StoryBuilderView.as_view(), name='story_builder'),
    url(r'^build/(?P<story_id>{})/(?P<step>data|tag|info|publish)/$'.format(uuid_pattern),
        StoryBuilderView.as_view(), name='story_builder'),
    url(r'^explore/$', ExploreStoriesView.as_view(), name='explore_stories'),
    url(r'^stories/(?P<story_id>{})/$'.format(uuid_pattern),
        StoryDetailView.as_view(), name='story_detail_by_id'),
    url(r'^stories/(?P<slug>[0-9a-z-]+)/$',
        StoryDetailView.as_view(), name='story_detail'),
    url(r'^stories/(?P<story_id>{})/viewer/$'.format(uuid_pattern),
        StoryViewerView.as_view(), name='story_viewer_by_id'),
    url(r'^stories/(?P<slug>[0-9a-z-]+)/viewer/$',
        StoryViewerView.as_view(), name='story_viewer'),
    url(r'^stories/(?P<story_id>{})/preview/$'.format(uuid_pattern),
        StoryViewerView.as_view(), kwargs={'preview': True},
        name='story_viewer_preview'),
    url(r'^stories/(?P<slug>[0-9a-z-]+)/preview/$',
        StoryViewerView.as_view(), kwargs={'preview': True},
        name='story_viewer_preview'),
    url(r'stories/(?P<source_story_id>{})/build-connected/$'.format(uuid_pattern),
        StoryBuilderView.as_view(),
        {'template': settings.STORYBASE_CONNECTED_STORY_TEMPLATE},
        name='connected_story_builder'),
    url(r'stories/(?P<source_slug>[0-9a-z-]+)/build-connected/$',
        StoryBuilderView.as_view(),
        {'template': settings.STORYBASE_CONNECTED_STORY_TEMPLATE},
        name='connected_story_builder'),
    url(r'stories/(?P<source_story_id>{0})/build-connected/(?P<story_id>{0})/$'.format(uuid_pattern),
        StoryBuilderView.as_view(),
        {'template': settings.STORYBASE_CONNECTED_STORY_TEMPLATE},
        name='connected_story_builder'),
    url(r'stories/(?P<source_slug>[0-9a-z-]+)/build-connected/(?P<story_id>{})/$'.format(uuid_pattern),
        StoryBuilderView.as_view(),
        {'template': settings.STORYBASE_CONNECTED_STORY_TEMPLATE},
        name='connected_story_builder'),
    url(r'^stories/(?P<story_id>{})/share/$'.format(uuid_pattern),
        StoryShareView.as_view(), name='story_share'),
    url(r'^stories/(?P<slug>[0-9a-z-]+)/share/$',
        StoryShareView.as_view(), name='story_share'),
    url(r'^stories/(?P<story_id>{})/share/popup/$'.format(uuid_pattern),
        StorySharePopupView.as_view(), name='story_share_popup'),
    url(r'^stories/(?P<slug>[0-9a-z-]+)/share/popup/$',
        StorySharePopupView.as_view(), name='story_share_popup'),
    url(r'^stories/(?P<story_id>{})/embed/$'.format(uuid_pattern),
        StoryEmbedView.as_view(), name='story_embed'),
    url(r'^stories/(?P<slug>[0-9a-z-]+)/embed/$',
        StoryEmbedView.as_view(), name='story_embed'),
    url(r'^stories/(?P<story_id>{})/embed/popup/$'.format(uuid_pattern),
        StoryEmbedPopupView.as_view(), name='story_embed_popup'),
    url(r'^stories/(?P<slug>[0-9a-z-]+)/embed/popup/$',
        StoryEmbedPopupView.as_view(), name='story_embed_popup'),
    url(r'^stories/(?P<slug>[0-9a-z-]+)/unpublish/$',  
        StoryUpdateView.as_view(), {'status': 'draft'}, 
        name='story_unpublish'), 
    url(r'^stories/(?P<slug>[0-9a-z-]+)/publish/$',  
        StoryUpdateView.as_view(), {'status': 'published'}, 
        name='story_publish'),
    url(r'^stories/(?P<slug>[0-9a-z-]+)/delete/$',  
        StoryUpdateView.as_view(), {'status': 'deleted'}, 
        name='story_delete'),
    url(r'^feeds/stories/$',
        StoriesFeed(), name='story_feed'),
    url(r'^feeds/topics/(?P<slug>[0-9a-z-]+)/$',
        TopicStoriesFeed(), name='topic_story_feed'),
)
